### PR TITLE
refactor prober_manager to update the runtime state

### PR DESCRIPTION
**Pull request by matthyx**
#### Which issue(s) this PR fixes:

Fixes #115937

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by xmcqueen — APPROVED** [review]
/lgtm

**Comment by gjkim42** [comment]
@matthyx 

Thanks.

Either this or https://github.com/kubernetes/kubernetes/issues/115937#issuecomment-1454511383 (not adding fields to `kubecontainer.ContainerStatus`) should be picked.
I personally prefer not to add fields to `kubecontainer.ContainerStatus` as it can minimize the changes to the existing code.

**Comment by matthyx** [comment]
> @matthyx
> 
> Thanks.
> 
> Either this or [kubernetes#115937 (comment)](https://github.com/kubernetes/kubernetes/issues/115937#issuecomment-1454511383) (not adding fields to `kubecontainer.ContainerStatus`) should be picked. I personally prefer not to add fields to `kubecontainer.ContainerStatus` as it can minimize the changes to the existing code.

Will you be available to discuss that during the workgroup meeting?

**Comment by gjkim42** [comment]
> Will you be available to discuss that during the workgroup meeting?

I am not sure as it will be too late for me. I'll be there if available.

**Comment by matthyx** [comment]
> I am not sure as it will be too late for me. I'll be there if available.

Alright, in any case I have added the point to the meeting, and I will discuss that on your behalf if you're not here.

**Pull request closed without merging**
