### PR TITLE
sidecar: Add RestartPolicy field to Container type

### PR DESCRIPTION
**Pull request by gjkim42**
**What type of PR is this?**

/kind api-change

**What this PR does / why we need it**:

3 commits:
1. add the SidecarContaienrs feature gate
1. add RestartPolicy to Container and EphemeralContainerCommon
1. add validation for RestartPolicy

xref: https://github.com/kubernetes/kubernetes/issues/115934

k/k PR: https://github.com/kubernetes/kubernetes/pull/115942 to test

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by gjkim42** [comment]
@SergeyKanzhelev 

I think there are some issues.

1. We need to add a feature gate and add `+featureGate:sidecar` to each restartPolicy field. (Is it ok to add it from this PR?)
2. https://github.com/SergeyKanzhelev/kubernetes/blob/ebcae8ff2c74f269bfea5caa9b083bb48473eb43/pkg/apis/core/types.go#L3029-L3031
I think we should either break this compatibility or add `restartPolicy` to `ephemeralContainerCommon` as well.

**Comment by gjkim42** [comment]
> 2\. I think we should either break this compatibility or add `restartPolicy` to `ephemeralContainerCommon` as well.

For now, I just added `restartPolicy` field to `ephemeralContainerCommon` as well. 

> * [ ]  API change - add restartPolicy to Init containers
> * [ ]  API validation - only allow restartPolicy for Init containers

Done these two parts. Please take a look.

---

<del>
I think maybe it is relatively ok to make `Container` and `EphemeralContainerCommon` unconvertible than to split `InitContainer` and `Container` as it does not directly break client-go compatibility.

If we make them unconvertible, we can make fewer API changes. However, there will be some extra work to fix that conversion part.

What do you think?

</del>

UPDATED:
[In-place Pod Vertical Scaling PR](https://github.com/kubernetes/kubernetes/pull/102884) also adds the `ResizePolicy` field to the `Container` and `EphemeralContainerCommon` although it only can be set in regular containers.
I think we can also add `RestartPolicy` field to both type.

**Comment by gjkim42** [comment]
- added the feature gate and fix the validation according to the feature gate
- passed [k/k CI](https://github.com/kubernetes/kubernetes/pull/115942). 

This is ready to review.

**Comment by gjkim42** [comment]
rebased and fixed all conflicts from the vertical pod scaling PR.

**Review by SergeyKanzhelev — APPROVED** [review]

**Pull request merged**
